### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by tbergen1** [Bugsy280779/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your slides are well done.  They are clean and display all of the relevant data in a nice format.  You did a great job supporting your conclusions with the data from your queries.  I also really liked your breakdown of the first usage funnel (quiz).  Great work!

### Criteria 2: Query Accuracy
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: All queries accurately retrieve the data intended.  Great job!

### Criteria 3: Query Formatting
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Queries adhere to the rules of the style guide.  Formatting is important, especially in larger queries, so it is great that you paid attention to this area.

### Criteria 4: Understanding underlying concepts and terminology
* **Score Level**: 4/4 (Exceeds Expectations)
* *Comment(s)*: Your report demonstrated an understanding of the concepts of funnel analysis.  You provided good insight into what funnel analysis is used for as well as what business insights can be gleaned from its application.  You also gave good advice to the company regarding what course it should take based on the funnel data.  Great job!

### Overall Score: 16/16
Overall, you did a great job with this.  You demonstrated clear understanding of the material and developed a good looking, clean report on your findings.  All of your conclusions were supported with evidence coming from well-formatted, accurate queries.  Keep up the good work!

**Comment by Bugsy280779** [comment]
Thank you. This was an enjoyable course and extremely well tailored to the absolute beginner.
